name: Build EPUB
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        default: 'v2'
        type: choice
        options:
          - v2
          - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0 # 关键修复：关闭浅克隆

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y pandoc make

      - name: Install Go
        run: |
          curl -OL https://go.dev/dl/go1.27.2.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go
          sudo tar -C /usr/local -xzf go1.27.2.linux-amd64.tar.gz
          echo "PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV

      - name: Go mod download
        run: go mod download

      - name: Build EPUB
        run: make epub

      - name: Upload EPUB artifact
        uses: actions/upload-artifact@v4
        with:
          name: ddia-epub
          path: output/ddia.epub
